name: ZUCC Auto Check

on:
  workflow_dispatch:
  schedule:
    - cron: '31 16 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Auto Check
        env:
          SCHOOL_ID: ${{ secrets.SCHOOL_ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LOCATION: ${{ secrets.LOCATION }}
          AUTO_POSITION: ${{ secrets.AUTO_POSITION }}
          VACCINE: ${{ secrets.VACCINE }}
          SCKEY: ${{ secrets.SCKEY }}
        run: python main.py
      - name: Auto Check 2
        env:
          SCHOOL_ID: 32109113
          PASSWORD: 156843
          LOCATION: ${{ secrets.LOCATION }}
          AUTO_POSITION: ${{ secrets.AUTO_POSITION }}
          VACCINE: 已接种两针剂疫苗（科兴、生物等）第二针
          SCKEY: ${{ secrets.SCKEY }}
        run: python main.py
